#!/bin/sh

# Store the staged files and biome.json in variables
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR)
BIOME_FILE=$(git ls-files --full-name --error-unmatch biome.json)

# Combine the staged files and biome.json
STAGED_FILES="$STAGED_FILES"$'\n'"$BIOME_FILE"

# Exit early if no relevant files are staged
if [ -z "$STAGED_FILES" ]; then
    echo "No relevant files to check."
    exit 0
fi

# Create a temporary file to store the file list
TEMP_FILE=$(mktemp)
echo "$STAGED_FILES" >"$TEMP_FILE"

# Run Biome check on the files from the temp file
xargs biome check --write --unsafe <"$TEMP_FILE"
CHECK_RESULT=$?

# Clean up the temporary file
rm "$TEMP_FILE"

# If Biome made changes, add them back to staging
if [ $CHECK_RESULT -eq 0 ]; then
    echo "$STAGED_FILES" | xargs git add

    exit 0
else
    echo "Biome check failed. Please fix the issues and try again."
    exit 1
fi
